DROP TABLE baseball_record;
DROP TABLE baseball_user;

CREATE TABLE baseball_user (
	user_id varchar2(50) NOT NULL PRIMARY KEY,
	password varchar2(255) NOT NULL,
	my_team varchar2(50) NOT NULL -- 나중에 테이블 분리도 가능
)

CREATE TABLE baseball_record (
	id number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	user_id varchar2(50) REFERENCES baseball_user (user_id),
	game_date DATE NOT NULL,
	stadium varchar2(50) NOT NULL, -- 나중에 테이블 분리도 가능
	home_team varchar2(50) NOT NULL, -- 나중에 테이블 분리도 가능
	away_team varchar2(50) NOT NULL, -- 나중에 테이블 분리도 가능
	home_starter varchar2(50),
	away_starter varchar2(50),
	home_score number NOT NULL,
	away_score number NOT NULL,
	game_result varchar2(10) NOT NULL,
	mvp varchar2(50),
	game_detail varchar2(2000),
	created_at DATE DEFAULT sysdate NOT NULL
);

INSERT INTO baseball_user
VALUES ('test', 'test1234', '삼성 라이온즈');

COMMIT;

INSERT INTO baseball_record (user_id, game_date, stadium, home_team, away_team, home_starter, away_starter, home_score, away_score, game_result, mvp, game_detail, created_at) 
VALUES ('test', TO_DATE('2024-05-15', 'YYYY-MM-DD'), '대구삼성라이온즈파크', '삼성 라이온즈', '두산 베어스', '이승현', '곽빈', 7, 3, '승', '구자욱', '4회말 구자욱 3점홈런으로 역전! 분위기 최고였음', SYSDATE);

INSERT INTO baseball_record (user_id, game_date, stadium, home_team, away_team, home_starter, away_starter, home_score, away_score, game_result, mvp, game_detail, created_at) 
VALUES ('test', TO_DATE('2024-06-22', 'YYYY-MM-DD'), '잠실야구장', 'LG 트윈스', '삼성 라이온즈', '임찬규', '원태인', 5, 2, '패', '오스틴', '원정 경기 아쉽게 졌지만 잠실 분위기는 좋았다', SYSDATE);

INSERT INTO baseball_record (user_id, game_date, stadium, home_team, away_team, home_starter, away_starter, home_score, away_score, game_result, mvp, game_detail, created_at) 
VALUES ('test', TO_DATE('2024-07-10', 'YYYY-MM-DD'), '대구삼성라이온즈파크', '삼성 라이온즈', 'KIA 타이거즈', '황동재', '양현종', 8, 4, '승', '김영웅', '김영웅 멀티히트! 라이온즈 파크 야경도 예뻤다', SYSDATE);


SELECT b.*
FROM (SELECT rownum rn, a.*
	  FROM (SELECT *
	  		FROM board
	  		ORDER BY 1) a ) b
WHERE b.rn > (:page -1) * 5
AND b.rn <= (:page * 5);

SELECT user_id
FROM baseball_user 
WHERE user_id = :user_id;